[package]
name = "desktop_cleaner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
trash = "4.1.1"
clap = { version = "4.0", features = ["derive"] }